source 'https://rubygems.org'
gem 'capistrano', '~> 3.18.0'
# We must use capistrano-passenger 0.0.2 for now, because later versions use
# Passenger's new restart mechanism, which requires sudo, and is therefore
# incompatible with our OIT VM setup. See this issue for details:
# https://github.com/capistrano/passenger/issues/2 
gem 'capistrano-passenger', '0.0.2'
gem 'capistrano-npm'
gem 'capistrano-umnlib-common', '>= 1.0.0', git: 'git@github.umn.edu:Libraries/capistrano-umnlib-common.git', branch: 'master'

gem "ed25519", "~> 1.3"
gem "bcrypt_pbkdf", "~> 1.1"
